# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does321"
  lane :build_test do
    sync_code_signing(
        type: "appstore",
        app_identifier: "ekko.Fastlane-Tutorial",
        readonly: true,
        git_url: "https://github.com/Ekko0701/Fastlane-Match.git"
    )
    gym(scheme: "Fastlane_Tutorial")
  end
  
  lane :build_test2 do
    authorization_token_str = ENV['TOKEN']
    basic_authorization_token = Base64.strict_encode64(authorization_token_str)
    
    create_keychain(
        name: ENV["KEYCHAIN_NAME"],
        password: ENV["KEYCHAIN_PASSWORD"],
        timeout: 1800,
        default_keychain: true,
        unlock: true,
        lock_when_sleeps: false
    )
    
    match(
        git_url: "https://github.com/Ekko0701/Fastlane-Match.git",
        git_basic_authorization: basic_authorization_token,
        storage_mode: "git",
        type: "appstore",
        readonly: true,
        app_identifier: "ekko.Fastlane-Tutorial",
        keychain_name: ENV["KEYCHAIN_NAME"],
        keychain_password: ENV["KEYCHAIN_PASSWORD"]
    )
    gym(scheme: "Fastlane_Tutorial")
  end
end
