# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :build_test do
    sync_code_signing(
        type: "appstore",
        app_identifier: "ekko.Fastlane-Tutorial",
        readonly: true,
        git_url: "https://github.com/Ekko0701/Fastlane-Match.git"
    )
    gym(scheme: "Fastlane_Tutorial")
  end
  
  lane :build_test2 do
    create_keychain(
        name: "CustomKeyChain",
        password: "12345!",
        timeout: 2000,
        default_keychain: true,
        unlock: true,
        lock_when_sleeps: false
    )
  
    match(
        git_url: "https://github.com/Ekko0701/Fastlane-Match.git",
        storage_mode: "git",
        type: "appstore",
        readonly: true,
        verbose: true
    )
    gym(scheme: "Fastlane_Tutorial")
  end
end
